### ISSUE TITLE
Proper usage of config files 

### ISSUE THREAD

**Issue by sarim-zafar** [zafargilani/uc#2]
Remove all the auth keys and use the config files appropriatly ... also gitignore the config file being used

**Comment by zafargilani** [comment]
I've added .gitignore, please handle the config files properly. There shouldn't be keys inside the code.

**Comment by sarim-zafar** [comment]
Done in latest commit ce735e75

**Comment by zafargilani** [comment]
Pulling latest commit (while retaining all the transformers and classifiers), the service dies because of keys/tokens not being read properly from the config file. Reverting the change in my local repository fixes the issue.

assert key not in self.keys
AssertionError

Please fix the issue.

**Comment by sarim-zafar** [comment]
Are you using the config file I sent you in the email?

**Comment by zafargilani** [comment]
Yes. This one with the keys of course:
[app]
ACCESS_TOKEN    = xyz
ACCESS_SECRET   = xyz
CONSUMER_KEY    = xyz
CONSUMER_SECRET = xyz
FRIENDS_TO_PULL = nnn

**Comment by sarim-zafar** [comment]
Make sure the file is named config.ini and is placed in the root of the directory.
It is working on my local repository.
Can you attach log of the error so I might be able to get a better understanding of the nature of error.

**Comment by zafargilani** [comment]
```
$ pwd
/home/szuhg2/uc
$ ls
app.py  bio  config.ini  hashtag  ids  LICENSE.txt  links  liveprediction.py  liveprediction.pyc  mention  __pycache__  README.md  tweets
```

Error log:
```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x}(TensorConstant{0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/tensor/opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1125, in module_from_key
    module = self._get_from_hash(module_hash, key, keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1025, in _get_from_hash
    key_data.add_key(key, save_pkl=bool(key[0]))
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cmodule.py", line 487, in add_key
    assert key not in self.keys
AssertionError

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/szuhg2/uc/liveprediction.py", line 290, in classify_links
    result=linksclf.predict(X_test)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/keras/models.py", line 939, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1745, in predict
    self._make_predict_function()
  File "/home/szuhg2/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1029, in _make_predict_function
    **kwargs)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 1232, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 1218, in __init__
    **kwargs)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/compile/function_module.py", line 1794, in orig_function
    output_keys=output_keys).create(
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/compile/function_module.py", line 1474, in __init__
    optimizer_profile = optimizer(fgraph)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 98, in __call__
    return self.optimize(fgraph)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 2497, in apply
    sub_prof = gopt.apply(fgraph)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 2095, in apply
    nb += self.process_node(fgraph, node)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 1987, in process_node
    lopt, node)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 1881, in warn_inplace
    return NavigatorOptimizer.warn(exc, nav, repl_pairs, local_opt, node)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 1867, in warn
    raise exc
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/tensor/opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1125, in module_from_key
    module = self._get_from_hash(module_hash, key, keep_lock=keep_lock)
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1025, in _get_from_hash
    key_data.add_key(key, save_pkl=bool(key[0]))
  File "/home/szuhg2/.local/lib/python3.5/site-packages/theano/gof/cmodule.py", line 487, in add_key
    assert key not in self.keys
AssertionError

INFO (theano.gof.compilelock): Waiting for existing lock by process '27196' (I am process '27196')
INFO (theano.gof.compilelock): To manually release the lock, delete /home/szuhg2/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '27196' (I am process '27196')
INFO (theano.gof.compilelock): To manually release the lock, delete /home/szuhg2/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64/lock_dir
INFO (theano.gof.compilelock): Waiting for existing lock by process '27196' (I am process '27196')
INFO (theano.gof.compilelock): To manually release the lock, delete /home/szuhg2/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64/lock_dir
[16/Nov/2017:10:01:41] ENGINE Keyboard Interrupt: shutting down bus
[16/Nov/2017:10:01:41] ENGINE Bus STOPPING

```

**Comment by sarim-zafar** [comment]
Make sure you kill all the python process' this seems like a theano based lock error and not related to the config file.I encountered this issue once...Restarting the computer did the trick. It is caused by crashing of program or thread during execution of the model which leads to Locks that arent released. I'd recommend a restart of your machine and see if that works

**Comment by zafargilani** [comment]
Not sure about that. As I mentioned when I reopened the issue the app works if I put the keys inside the code. There's some weird thing that doesn't read the config properly. I've the app running at the moment (URL in your email). Please check and respond. I'll see your activity in the logs on my screen.

**Comment by sarim-zafar** [comment]
Yes the server seems to be working .I'd still insist on deleting the lock file's manually or doing a plain restart to see if that resolve's the issue...Meanwhile I'll try to see if I can replicate your issue on some other computer as it is working fine on my computer

**Comment by zafargilani** [comment]
Resolved.

What needed to be done was:
- new session (instead of a restart)
- deleting lock dir

**Comment by sarim-zafar** [comment]
Great...
Lets add this in a faq's file
